-- 2a) 3 databases are created by the script.
-- 2b) 1. ap database and tables that are created under it are: general_ledger_accounts, terms, vendors,
--        invoices, invoice_line_items, vendor_contacts, invoice_archive.
--     2. ex database and tables that are created under it are: null_sample, departments, employees, projects,
--        customers, color_sample, string_sample, float_sample, date_sample, active_invoices, paid_invoices.
--     3. om database and tables that are created under it are: customers, items, orders, order_details.
--